create table if not exists public.eren_marketplace_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  game text not null check (char_length(game) between 1 and 80),
  comment text not null check (char_length(comment) between 1 and 800),
  created_at timestamptz not null default now()
);

create index if not exists eren_marketplace_comments_created_at_idx on public.eren_marketplace_comments (created_at desc);

create table if not exists public.eren_marketplace_packages (
  id bigint generated by default as identity primary key,
  game_name text not null,
  amount text not null,
  price numeric(12, 2) not null check (price >= 0),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists eren_marketplace_packages_game_active_idx on public.eren_marketplace_packages (game_name, is_active, id);

create table if not exists public.eren_marketplace_settings (
  id integer primary key default 1 check (id = 1),
  comments_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.eren_marketplace_settings (id, comments_enabled)
values (1, true)
on conflict (id) do nothing;

alter table public.eren_marketplace_comments enable row level security;
alter table public.eren_marketplace_packages enable row level security;
alter table public.eren_marketplace_settings enable row level security;
