create table if not exists public.eren_marketplace_orders (
  id bigint generated by default as identity primary key,
  game_name text not null,
  package_label text not null,
  price numeric(12,2) not null check (price > 0),
  customer_name text not null,
  customer_contact text not null,
  account_data text not null,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'contacted', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.eren_marketplace_orders enable row level security;

drop policy if exists "eren_orders_public_insert" on public.eren_marketplace_orders;
create policy "eren_orders_public_insert" on public.eren_marketplace_orders for insert to anon, authenticated with check (true);
